// generated by the @nuxtjs/tailwindcss <https://github.com/nuxt-modules/tailwindcss> module at 5/12/2026, 12:39:10 AM
import "@nuxtjs/tailwindcss/config-ctx"
import configMerger from "@nuxtjs/tailwindcss/merger";

import cfg2 from "./../../tailwind.config.ts";
const config = [
{"content":{"files":["C:/Users/HP/Downloads/yemen-flow-hub/frontend-nuxt/components/**/*.{vue,js,jsx,mjs,ts,tsx}","C:/Users/HP/Downloads/yemen-flow-hub/frontend-nuxt/components/global/**/*.{vue,js,jsx,mjs,ts,tsx}","C:/Users/HP/Downloads/yemen-flow-hub/frontend-nuxt/components/**/*.{vue,js,jsx,mjs,ts,tsx}","C:/Users/HP/Downloads/yemen-flow-hub/frontend-nuxt/layouts/**/*.{vue,js,jsx,mjs,ts,tsx}","C:/Users/HP/Downloads/yemen-flow-hub/frontend-nuxt/plugins/**/*.{js,ts,mjs}","C:/Users/HP/Downloads/yemen-flow-hub/frontend-nuxt/composables/**/*.{js,ts,mjs}","C:/Users/HP/Downloads/yemen-flow-hub/frontend-nuxt/utils/**/*.{js,ts,mjs}","C:/Users/HP/Downloads/yemen-flow-hub/frontend-nuxt/pages/**/*.{vue,js,jsx,mjs,ts,tsx}","C:/Users/HP/Downloads/yemen-flow-hub/frontend-nuxt/{A,a}pp.{vue,js,jsx,mjs,ts,tsx}","C:/Users/HP/Downloads/yemen-flow-hub/frontend-nuxt/{E,e}rror.{vue,js,jsx,mjs,ts,tsx}","C:/Users/HP/Downloads/yemen-flow-hub/frontend-nuxt/app.config.{js,ts,mjs}"]}},
{},
cfg2
].reduce((acc, curr) => configMerger(acc, curr), {});

const resolvedConfig = config;

export default resolvedConfig;