/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SettingsRouteImport } from './routes/settings'
import { Route as ReportsRouteImport } from './routes/reports'
import { Route as ProfileRouteImport } from './routes/profile'
import { Route as NotificationsRouteImport } from './routes/notifications'
import { Route as MerchantsRouteImport } from './routes/merchants'
import { Route as LoginRouteImport } from './routes/login'
import { Route as CustomsRouteImport } from './routes/customs'
import { Route as AuditRouteImport } from './routes/audit'
import { Route as IndexRouteImport } from './routes/index'
import { Route as RequestsIndexRouteImport } from './routes/requests.index'
import { Route as RequestsNewRouteImport } from './routes/requests.new'
import { Route as RequestsIdRouteImport } from './routes/requests.$id'
import { Route as BankUsersRouteImport } from './routes/bank.users'
import { Route as AdminWorkflowDocsRouteImport } from './routes/admin.workflow-docs'
import { Route as AdminRolesRouteImport } from './routes/admin.roles'
import { Route as AdminEntitiesRouteImport } from './routes/admin.entities'
import { Route as AdminCbyStaffRouteImport } from './routes/admin.cby-staff'
import { Route as RequestsIdSwiftRouteImport } from './routes/requests.$id.swift'
import { Route as CustomsIdPrintRouteImport } from './routes/customs.$id.print'

const SettingsRoute = SettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => rootRouteImport,
} as any)
const ReportsRoute = ReportsRouteImport.update({
  id: '/reports',
  path: '/reports',
  getParentRoute: () => rootRouteImport,
} as any)
const ProfileRoute = ProfileRouteImport.update({
  id: '/profile',
  path: '/profile',
  getParentRoute: () => rootRouteImport,
} as any)
const NotificationsRoute = NotificationsRouteImport.update({
  id: '/notifications',
  path: '/notifications',
  getParentRoute: () => rootRouteImport,
} as any)
const MerchantsRoute = MerchantsRouteImport.update({
  id: '/merchants',
  path: '/merchants',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const CustomsRoute = CustomsRouteImport.update({
  id: '/customs',
  path: '/customs',
  getParentRoute: () => rootRouteImport,
} as any)
const AuditRoute = AuditRouteImport.update({
  id: '/audit',
  path: '/audit',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const RequestsIndexRoute = RequestsIndexRouteImport.update({
  id: '/requests/',
  path: '/requests/',
  getParentRoute: () => rootRouteImport,
} as any)
const RequestsNewRoute = RequestsNewRouteImport.update({
  id: '/requests/new',
  path: '/requests/new',
  getParentRoute: () => rootRouteImport,
} as any)
const RequestsIdRoute = RequestsIdRouteImport.update({
  id: '/requests/$id',
  path: '/requests/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const BankUsersRoute = BankUsersRouteImport.update({
  id: '/bank/users',
  path: '/bank/users',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminWorkflowDocsRoute = AdminWorkflowDocsRouteImport.update({
  id: '/admin/workflow-docs',
  path: '/admin/workflow-docs',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRolesRoute = AdminRolesRouteImport.update({
  id: '/admin/roles',
  path: '/admin/roles',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminEntitiesRoute = AdminEntitiesRouteImport.update({
  id: '/admin/entities',
  path: '/admin/entities',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminCbyStaffRoute = AdminCbyStaffRouteImport.update({
  id: '/admin/cby-staff',
  path: '/admin/cby-staff',
  getParentRoute: () => rootRouteImport,
} as any)
const RequestsIdSwiftRoute = RequestsIdSwiftRouteImport.update({
  id: '/swift',
  path: '/swift',
  getParentRoute: () => RequestsIdRoute,
} as any)
const CustomsIdPrintRoute = CustomsIdPrintRouteImport.update({
  id: '/$id/print',
  path: '/$id/print',
  getParentRoute: () => CustomsRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/audit': typeof AuditRoute
  '/customs': typeof CustomsRouteWithChildren
  '/login': typeof LoginRoute
  '/merchants': typeof MerchantsRoute
  '/notifications': typeof NotificationsRoute
  '/profile': typeof ProfileRoute
  '/reports': typeof ReportsRoute
  '/settings': typeof SettingsRoute
  '/admin/cby-staff': typeof AdminCbyStaffRoute
  '/admin/entities': typeof AdminEntitiesRoute
  '/admin/roles': typeof AdminRolesRoute
  '/admin/workflow-docs': typeof AdminWorkflowDocsRoute
  '/bank/users': typeof BankUsersRoute
  '/requests/$id': typeof RequestsIdRouteWithChildren
  '/requests/new': typeof RequestsNewRoute
  '/requests/': typeof RequestsIndexRoute
  '/customs/$id/print': typeof CustomsIdPrintRoute
  '/requests/$id/swift': typeof RequestsIdSwiftRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/audit': typeof AuditRoute
  '/customs': typeof CustomsRouteWithChildren
  '/login': typeof LoginRoute
  '/merchants': typeof MerchantsRoute
  '/notifications': typeof NotificationsRoute
  '/profile': typeof ProfileRoute
  '/reports': typeof ReportsRoute
  '/settings': typeof SettingsRoute
  '/admin/cby-staff': typeof AdminCbyStaffRoute
  '/admin/entities': typeof AdminEntitiesRoute
  '/admin/roles': typeof AdminRolesRoute
  '/admin/workflow-docs': typeof AdminWorkflowDocsRoute
  '/bank/users': typeof BankUsersRoute
  '/requests/$id': typeof RequestsIdRouteWithChildren
  '/requests/new': typeof RequestsNewRoute
  '/requests': typeof RequestsIndexRoute
  '/customs/$id/print': typeof CustomsIdPrintRoute
  '/requests/$id/swift': typeof RequestsIdSwiftRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/audit': typeof AuditRoute
  '/customs': typeof CustomsRouteWithChildren
  '/login': typeof LoginRoute
  '/merchants': typeof MerchantsRoute
  '/notifications': typeof NotificationsRoute
  '/profile': typeof ProfileRoute
  '/reports': typeof ReportsRoute
  '/settings': typeof SettingsRoute
  '/admin/cby-staff': typeof AdminCbyStaffRoute
  '/admin/entities': typeof AdminEntitiesRoute
  '/admin/roles': typeof AdminRolesRoute
  '/admin/workflow-docs': typeof AdminWorkflowDocsRoute
  '/bank/users': typeof BankUsersRoute
  '/requests/$id': typeof RequestsIdRouteWithChildren
  '/requests/new': typeof RequestsNewRoute
  '/requests/': typeof RequestsIndexRoute
  '/customs/$id/print': typeof CustomsIdPrintRoute
  '/requests/$id/swift': typeof RequestsIdSwiftRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/audit'
    | '/customs'
    | '/login'
    | '/merchants'
    | '/notifications'
    | '/profile'
    | '/reports'
    | '/settings'
    | '/admin/cby-staff'
    | '/admin/entities'
    | '/admin/roles'
    | '/admin/workflow-docs'
    | '/bank/users'
    | '/requests/$id'
    | '/requests/new'
    | '/requests/'
    | '/customs/$id/print'
    | '/requests/$id/swift'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/audit'
    | '/customs'
    | '/login'
    | '/merchants'
    | '/notifications'
    | '/profile'
    | '/reports'
    | '/settings'
    | '/admin/cby-staff'
    | '/admin/entities'
    | '/admin/roles'
    | '/admin/workflow-docs'
    | '/bank/users'
    | '/requests/$id'
    | '/requests/new'
    | '/requests'
    | '/customs/$id/print'
    | '/requests/$id/swift'
  id:
    | '__root__'
    | '/'
    | '/audit'
    | '/customs'
    | '/login'
    | '/merchants'
    | '/notifications'
    | '/profile'
    | '/reports'
    | '/settings'
    | '/admin/cby-staff'
    | '/admin/entities'
    | '/admin/roles'
    | '/admin/workflow-docs'
    | '/bank/users'
    | '/requests/$id'
    | '/requests/new'
    | '/requests/'
    | '/customs/$id/print'
    | '/requests/$id/swift'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuditRoute: typeof AuditRoute
  CustomsRoute: typeof CustomsRouteWithChildren
  LoginRoute: typeof LoginRoute
  MerchantsRoute: typeof MerchantsRoute
  NotificationsRoute: typeof NotificationsRoute
  ProfileRoute: typeof ProfileRoute
  ReportsRoute: typeof ReportsRoute
  SettingsRoute: typeof SettingsRoute
  AdminCbyStaffRoute: typeof AdminCbyStaffRoute
  AdminEntitiesRoute: typeof AdminEntitiesRoute
  AdminRolesRoute: typeof AdminRolesRoute
  AdminWorkflowDocsRoute: typeof AdminWorkflowDocsRoute
  BankUsersRoute: typeof BankUsersRoute
  RequestsIdRoute: typeof RequestsIdRouteWithChildren
  RequestsNewRoute: typeof RequestsNewRoute
  RequestsIndexRoute: typeof RequestsIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/settings': {
      id: '/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof SettingsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/reports': {
      id: '/reports'
      path: '/reports'
      fullPath: '/reports'
      preLoaderRoute: typeof ReportsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/profile': {
      id: '/profile'
      path: '/profile'
      fullPath: '/profile'
      preLoaderRoute: typeof ProfileRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/notifications': {
      id: '/notifications'
      path: '/notifications'
      fullPath: '/notifications'
      preLoaderRoute: typeof NotificationsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/merchants': {
      id: '/merchants'
      path: '/merchants'
      fullPath: '/merchants'
      preLoaderRoute: typeof MerchantsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/customs': {
      id: '/customs'
      path: '/customs'
      fullPath: '/customs'
      preLoaderRoute: typeof CustomsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/audit': {
      id: '/audit'
      path: '/audit'
      fullPath: '/audit'
      preLoaderRoute: typeof AuditRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/requests/': {
      id: '/requests/'
      path: '/requests'
      fullPath: '/requests/'
      preLoaderRoute: typeof RequestsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/requests/new': {
      id: '/requests/new'
      path: '/requests/new'
      fullPath: '/requests/new'
      preLoaderRoute: typeof RequestsNewRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/requests/$id': {
      id: '/requests/$id'
      path: '/requests/$id'
      fullPath: '/requests/$id'
      preLoaderRoute: typeof RequestsIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/bank/users': {
      id: '/bank/users'
      path: '/bank/users'
      fullPath: '/bank/users'
      preLoaderRoute: typeof BankUsersRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/workflow-docs': {
      id: '/admin/workflow-docs'
      path: '/admin/workflow-docs'
      fullPath: '/admin/workflow-docs'
      preLoaderRoute: typeof AdminWorkflowDocsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/roles': {
      id: '/admin/roles'
      path: '/admin/roles'
      fullPath: '/admin/roles'
      preLoaderRoute: typeof AdminRolesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/entities': {
      id: '/admin/entities'
      path: '/admin/entities'
      fullPath: '/admin/entities'
      preLoaderRoute: typeof AdminEntitiesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/cby-staff': {
      id: '/admin/cby-staff'
      path: '/admin/cby-staff'
      fullPath: '/admin/cby-staff'
      preLoaderRoute: typeof AdminCbyStaffRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/requests/$id/swift': {
      id: '/requests/$id/swift'
      path: '/swift'
      fullPath: '/requests/$id/swift'
      preLoaderRoute: typeof RequestsIdSwiftRouteImport
      parentRoute: typeof RequestsIdRoute
    }
    '/customs/$id/print': {
      id: '/customs/$id/print'
      path: '/$id/print'
      fullPath: '/customs/$id/print'
      preLoaderRoute: typeof CustomsIdPrintRouteImport
      parentRoute: typeof CustomsRoute
    }
  }
}

interface CustomsRouteChildren {
  CustomsIdPrintRoute: typeof CustomsIdPrintRoute
}

const CustomsRouteChildren: CustomsRouteChildren = {
  CustomsIdPrintRoute: CustomsIdPrintRoute,
}

const CustomsRouteWithChildren =
  CustomsRoute._addFileChildren(CustomsRouteChildren)

interface RequestsIdRouteChildren {
  RequestsIdSwiftRoute: typeof RequestsIdSwiftRoute
}

const RequestsIdRouteChildren: RequestsIdRouteChildren = {
  RequestsIdSwiftRoute: RequestsIdSwiftRoute,
}

const RequestsIdRouteWithChildren = RequestsIdRoute._addFileChildren(
  RequestsIdRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuditRoute: AuditRoute,
  CustomsRoute: CustomsRouteWithChildren,
  LoginRoute: LoginRoute,
  MerchantsRoute: MerchantsRoute,
  NotificationsRoute: NotificationsRoute,
  ProfileRoute: ProfileRoute,
  ReportsRoute: ReportsRoute,
  SettingsRoute: SettingsRoute,
  AdminCbyStaffRoute: AdminCbyStaffRoute,
  AdminEntitiesRoute: AdminEntitiesRoute,
  AdminRolesRoute: AdminRolesRoute,
  AdminWorkflowDocsRoute: AdminWorkflowDocsRoute,
  BankUsersRoute: BankUsersRoute,
  RequestsIdRoute: RequestsIdRouteWithChildren,
  RequestsNewRoute: RequestsNewRoute,
  RequestsIndexRoute: RequestsIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
